baseurl: "/RBLAC-SIGNATURE-SOLUTIONS"
plugins:
    - jekyll-seo-tag
gems:
  - jekyll-email-protect
exclude:
  - README.md
  - markdown_sample.md
  - Tutorials/
  - vendor
  - CNAME
  - README.md
  - node_modules
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - packages
  - bin